### post team
POST http://localhost:3000/teams
Content-Type: application/json

{
    "description": "Team wow"
}

### delete team
DELETE http://localhost:3000/teams/7
Content-Type: application/json

### post team
PATCH http://localhost:3000/teams/2
Content-Type: application/json

{
    "description": "Cramer l'opposition"
}

### GET TYPES
GET http://localhost:3000/types
Content-Type: application/json

###
GET http://localhost:3000/pokemonsoftype/1
Content-Type: application/json
